exports.ERROR_MESSAGE = {
  SOMETHING_WENT_WRONG: "Something went wrong",
  EMAIL_ALREADY_EXIST: "Email already exists!",
  UNAUTHORIZED_USER: "You are not authorized",
  INVALID_TOKEN: "Invalid or expired verification token.",
  INVALID_EMAIL_PASSWORD: "Invalid email or password",
  USER_NOT_ACTIVE: "Your account is not active",
  USER_NOT_FOUND: "User not found",
  AUCTION_CATEGORY_EXIST: "Auction category already present",
  TOKEN_REQUIRED: "Token required",
  AUCTION_ID_REQUIRED: "Auction id required",
  AUCTION_NOT_FOUND: "Auction not found",
  CANNOT_BID_OWN_AUCTION: "You cannot bid on your own auction",
  BID_AMT_LESS: "Bid amount always grater than base amount",
  BID_ALREADY_APPLIED: "Bid already applied",
  CONTACT_NOT_FOUND: "Contact not found",
  CONTACT_ALREADY_EXIST: "Contact already exist",
  CONTACT_ID_REQUIRED: "Contact id required",
  CONTACT_NOT_UPDATE:"No contact found or status already set",
  CHAT_NOT_UPDATE:"No chat found or status already set",
  CHAT_NOT_FOUND: "Chat not found",
  UNAUTHORIZED_SUPERADMIN: "You are not authorized to perform this action",

};

exports.SUCCESS_MESSAGE = {
  DATA_FETCH_SUCCESSFULLY: "Data fetch successfully",
  USER_CREATED: "User created successfully",
  ACCOUNT_VERIFIED: "Account verified successfully",
  USER_LOGIN: "User successfully login",
  FORGOT_EMAIL_SEND: "Send a email for update password",
  PASSWORD_UPDATED: "Password updated successfully",
  AUCTION_CATEGORY_CREATED: "Auction category created successfully",
  AUCTION_CREATED: "Auction created successfully",
  AUCTION_UPDATED: "Auction updated successfully",
  BID_CREATE: "Bid created successfully",
  CONTACT_CREATED: "Contact created successfully",
  CONTACT_UPDATED: "Contact updated successfully",
  CONTACT_DELETED: "Contact deleted successfully",
  CONTACT_FETCHED: "Contact fetched successfully",
  CONTACT_STATUS_CHANGED: "Contact status changed successfully",
  CONTACT_ACTIVITY_CHANGED: "Contact Activity changed successfully",
  CHAT_CREATED: "Chat created successfully",
  CHAT_FETCHED: "Chat fetched successfully",
  CHAT_UPDATED: "Chat updated successfully",
  CHAT_DELETED: "Chat deleted successfully",
  CHAT_STATUS_CHANGED: "Chat status changed successfully",
  CHAT_ACTIVITY_CHANGED: "Chat Activity changed successfully",
  CHAT_REPLAY: "Send Message successfully",
  CHAT_ACTIVITY: "Chat activity changed successfully",
  
  
  

};
